Add `ADTHAUT` to adsl
insightsengineering/random.cdisc.data pull request #200
Opened 2022-09-09 17:00 UTC by edelarua

Closes #199

2022-09-12 23:57 UTC, shajoezhu requested changes
Hi @edelarua , thanks for the changes. `ADTHAUT` looks good. Seems that you have also updated some paths for the data, can you change them back please. Thanks!

2022-09-12 23:57 UTC, shajoezhu commented on vignettes/rebuild_cached_data.Rmd
> +save(cadhy, file = "C:/Users/delaruae/NEST/random.cdisc.data/data/cadhy.RData", compress = "xz")
Please revert this paths.

2022-09-12 23:57 UTC, shajoezhu commented on vignettes/rebuild_cached_data.Rmd
> +The following script is used to create, compare and save cached data to `C:/Users/delaruae/NEST/random.cdisc.data/data/` directory.
please revert this change

2022-09-13 00:22 UTC, edelarua commented
Hey @shajoezhu sorry about that, the paths have been reverted and it should be good to go now.

2022-09-13 01:06 UTC, shajoezhu approved these changes
brilliant! Thanks @edelarua

2022-09-13 01:06 UTC, merged